In [3]:
import numpy as np
np_array =np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [4]:
import numpy as np 
np_array =np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]
                    ])
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
import numpy as np 
ones_array = np.ones((5,5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [1]:
import numpy as np 
custom_arr = np.full((5,5),18)
print(custom_arr)

[[18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]


In [10]:
import numpy as np
arange_fn=np.arange(1,50,5)
print(arange_fn)

[ 1  6 11 16 21 26 31 36 41 46]


In [11]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
import numpy as np 

arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2d.shape)

(2, 3)


In [3]:
import numpy as np 

arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2d.size)

6


In [6]:
import numpy as np 
np_array =np.array([1,2,3,4])
arr_2d = np.array([[1,2,3],
                  [4,5,6]])
arr = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],
                 
                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print(np_array.ndim)
print(arr_2d.ndim)
print(arr.ndim)

1
2
3


In [14]:
#import numpy as np 
 #arr= np.array([1,2,3.4,5,7])
#print("arr.dtype")
import numpy as np 
arr= np.array([1,2,3.4,5,7])
print("arr.dtype")

arr.dtype


In [40]:
import numpy as np 
float_arr=([1.1,2.2,3.3,4.4,5.5])
arr=arr.astype(int)
print(float_arr)

[1.1, 2.2, 3.3, 4.4, 5.5]


In [48]:
import numpy as np 
arr=np.array([2,4,3])
print(arr +5)
print(arr *2)
print(arr**2)

[7 9 8]
[4 8 6]
[ 4 16  9]


In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print("Mean of array:", np.mean(arr))
print("Maximum value in array:", np.max(arr))
print("Minimum value in array:", np.min(arr))
print("Standard deviation of array:", np.std(arr))
print("Variance of array:", np.var(arr))
print("Again, Mean of array:", np.mean(arr))


Mean of array: 2.5
Maximum value in array: 4
Minimum value in array: 1
Standard deviation of array: 1.118033988749895
Variance of array: 1.25
Again, Mean of array: 2.5


In [4]:
import numpy as np 
arr= np.array([1,2,3,4,5,6])

print(arr[0])#
print(arr[-1])#6

1
6


In [26]:
import numpy as np 
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(arr2d[1, 1])  # Output: 6 (row 1, column 2)
#indexing start with zero...


5


In [ ]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8,9])

print("slicing",arr[1:5])#index 1 to 5 
print("slicing",arr[::-1])#reversr
print("slicing",arr[:5])#5 tak 
print("slicing",arr[::2])#every second element 

slicing [2 3 4 5]
slicing [9 8 7 6 5 4 3 2 1]
slicing [1 2 3 4 5]
slicing [1 3 5 7 9]


In [19]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[[0,2,4]])   # Output: [10 30 50]


[10 30 50]


In [31]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[[0, 1, 2],[0, 2, 2]])  # Output: [1 5 9]


[1 6 9]


In [30]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[arr>10])   # Output: [10 30 50]


[20 30 40 50]


In [54]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [56]:
#np.insert(arr, index, values, axis=None)

import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

in_arr =np.insert(arr,3,5)
print(in_arr)

[1 2 3 4 5 6]
[1 2 3 5 4 5 6]


In [36]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

merged = np.concatenate((a, b))
print(merged)


[1 2 3 4 5 6]


In [2]:
#np.delete(arr, index, axis=None)

import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

in_arr =np.delete(arr,5)
print(in_arr)

[1 2 3 4 5 6]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

new_arr = np.delete(arr, 1, axis=0)
print(new_arr)


[[1 2 3]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]])
arr1 = np.delete(arr, 2, axis=1)
print(arr1)


[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [14]:
import numpy as np

# 1D Arrays
a = np.array([1, 2])
b = np.array([3, 4])

# Vertical Stack (Top to Bottom)
v_result = np.vstack((a, b))
print("Vertical Stack (vstack):")
print(v_result)

# Horizontal Stack (Side by Side)
h_result = np.hstack((a, b))
print("\nHorizontal Stack (hstack):")
print(h_result)


Vertical Stack (vstack):
[[1 2]
 [3 4]]

Horizontal Stack (hstack):
[1 2 3 4]


In [37]:
#Splitting Arrays in NumPy
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
split_arr=np.split(arr,3)
print(split_arr)





[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [38]:
import numpy as np 
arr= np.array([1,2,3,4,5,6])
sum=np.sum(arr)
print(sum)

21


In [ ]:
#dicount apply

import numpy as np 
price =np.array([10,200,300,400,500])
discount =10
final_price=price -(price*discount/100)
print(final_price)

[  9. 180. 270. 360. 450.]


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])

mul=arr*2

print(mul)

[ 2  4  6  8 10]


In [46]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6]])
vector =np.array([1,2,3])
add =matrix + vector
print(add)

[[2 4 6]
 [5 7 9]]


In [48]:
#is nan 

import numpy as np 

arr=np.array([1,np.nan,22,3,np.nan,89])

a=np.isnan(arr)
print(a)

[False  True False False  True False]


In [ ]:
import numpy as np 
arr=np.array([1,2,3,np.nan,8,np.nan])
replaced_value =np.nan_to_num(arr)#deafult set be zero 
print("")
replaced_value =np.nan_to_num(arr,3,nan=4)
print(replaced_value)


[1. 2. 3. 4. 8. 4.]


In [1]:
import numpy as np

orignal_price=np.array([100,200,300,400,500])
discount=10
final_price=orignal_price-(orignal_price*discount/100)

print(final_price)

[ 90. 180. 270. 360. 450.]


In [ ]:
#project
